export const GET_POSITION_DETAIL = 'GET_POSITION_DETAIL'
export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST'
export const LETTERS_CONFIG = 'LETTERS_CONFIG'
export const CITY = 'CITY'
export const IS_SHOW_QUERY_SELETOR = 'IS_SHOW_QUERY_SELETOR'
export const IS_SHOW_CITY_BOX = 'IS_SHOW_CITY_BOX'


