export const GET_HOT_POSITION = 'GET_HOT_POSITION'
export const GET_HOT_INDUSTRY = 'GET_HOT_INDUSTRY'
export const GET_POSITION_LIST = 'GET_POSITION_LIST'
export const GET_JOB_HUNTING_TREASURE = 'GET_JOB_HUNTING_TREASURE'
export const GET_USER_DETAIL = 'GET_USER_DETAIL'
export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST'
export const LETTERS_CONFIG = 'LETTERS_CONFIG'
export const CITY = 'CITY'
export const IS_SHOW_QUERY_SELETOR = 'IS_SHOW_QUERY_SELETOR'
export const IS_SHOW_CITY_BOX = 'IS_SHOW_CITY_BOX'


